// defaultValues.js

import { closedDate } from "./validation";

export const defaultValue = {
  userAcc: {
    idPrefix: "",
    idNumber: "",
    firstName: "",
    lastName: "",
    middleName: "",
    userRoleId: null,
    sex: "",
    username: "",
    password: "",
  },
  report: {
    syncId: 0,
    mark1: null,
    mark2: null,
    assetCIP: null,
    accountingTag: null,
    transactionDate: null,
    clientSupplier: null,
    accountTitleCode: null,
    accountTitle: null,
    companyCode: null,
    company: null,
    divisionCode: null,
    division: null,
    departmentCode: null,
    department: null,
    unitCode: null,
    unit: null,
    subUnitCode: null,
    subUnit: null,
    locationCode: null,
    location: null,
    poNumber: null,
    referenceNo: null,
    itemCode: null,
    itemDescription: null,
    quantity: 0,
    uom: null,
    unitPrice: 0,
    lineAmount: 0,
    voucherJournal: null,
    accountType: null,
    drcr: null,
    assetCode: null,
    asset: null,
    serviceProviderCode: null,
    serviceProvider: null,
    boa: null,
    allocation: null,
    accountGroup: null,
    accountSubGroup: null,
    financialStatement: null,
    unitResponsible: null,
    batch: null,
    remarks: null,
    payrollPeriod: null,
    position: null,
    payrollType: null,
    payrollType2: null,
    depreciationDescription: null,
    remainingDepreciationValue: null,
    usefulLife: null,
    month: null,
    year: null,
    particulars: null,
    month2: null,
    farmType: null,
    adjustment: null,
    from: null,
    changeTo: null,
    reason: null,
    checkingRemarks: null,
    boA2: null,
    system: null,
    books: null,
  },

  system: {
    systemName: "",
    endpoint: "",
    token: "",
    iconFile: "",
    bookParameter: []
    
  },
  closedDate: {
    closedDate: 0,
  },
};

// You can export defaultReport or put it into a larger schema if needed.
