import moment from "moment";

export const transformRows = (data) => {
  return data.map((row, index) => ({
    ...row,
    id: row.id ?? index, // Unique identifier

    syncId: row.syncId ? row.syncId.toString() : "",
    mark1: row.mark1 || "",
    mark2: row.mark2 || "",
    assetCIP: row.assetCIP || "",
    accountingTag: row.accountingTag ? row.accountingTag.toString() : "",
    transactionDate: row.transactionDate
      ? moment(row.transactionDate, "MM/DD/YYYY").utc().toISOString()
      : "",
    clientSupplier: row.clientSupplier || "",
    accountTitleCode: row.accountTitleCode || "",
    accountTitle: row.accountTitle || "",
    companyCode: row.companyCode || "",
    company: row.company || "",
    divisionCode: row.divisionCode || "",
    division: row.division || "",
    departmentCode: row.departmentCode || "",
    department: row.department || "",
    unitCode: row.unitCode || "",
    unit: row.unit || "",
    subUnitCode: row.subUnitCode || "",
    subUnit: row.subUnit || "",
    locationCode: row.locationCode || "",
    location: row.location || "",
    poNumber: row.poNumber || "",
    rrNumber: row.rrNumber || "",
    referenceNo: row.referenceNo ? row.referenceNo.toString() : "",
    itemCode: row.itemCode || "",
    itemDescription: row.itemDescription || "",
    quantity: row.quantity || 0,
    uom: row.uom || "",
    unitPrice: row.unitPrice || 0,
    lineAmount: row.lineAmount || 0,
    voucherJournal: row.voucherJournal || "",
    accountType: row.accountType || "",
    drcp: row.drcp || "",
    assetCode: row.assetCode || "",
    asset: row.asset || "",
    serviceProviderCode: row.serviceProviderCode || "",
    serviceProvider: row.serviceProvider || "",
    boa: row.boa || "",
    allocation: row.allocation || "",
    accountGroup: row.accountGroup || "",
    accountSubGroup: row.accountSubGroup || "",
    financialStatement: row.financialStatement || "",
    unitResponsible: row.unitResponsible || "",
    batch: row.batch || "",
    remarks: row.remarks || "",
    payrollPeriod: row.payrollPeriod || "",
    position: row.position || "",
    payrollType: row.payrollType || "",
    payrollType2: row.payrollType2 || "",
    depreciationDescription: row.depreciationDescription || "",
    remainingDepreciationValue: row.remainingDepreciationValue || "",
    usefulLife: row.usefulLife || "",
    month: row.month || "",
    year: row.year || "",
    particulars: row.particulars || "",
    month2: row.month2 || "",
    farmType: row.farmType || "",
    jeanRemarks: row.jeanRemarks || "",
    from: row.from || "",
    changedTo: row.changedTo || "",
    reason: row.reason || "",
    checkingRemarks: row.checkingRemarks || "",
    bankName: row.bankName || "",
    chequeNumber: row.chequeNumber || "",
    chequeVoucherNumber: row.chequeVoucherNumber || "",
    boA2: row.boA2 || "",
    system: row.system || "",
    books: row.books || "",
  }));
};
