import {
  AccountBalanceOutlined,
  AccountBalanceRounded,
  CircleOutlined,
  CircleRounded,
  DashboardOutlined,
  DashboardRounded,
  EventNoteOutlined,
  EventNoteRounded,
  FeedOutlined,
  FeedRounded,
  ForestOutlined,
  ForestRounded,
  LeaderboardOutlined,
  LeaderboardRounded,
  PersonOutline,
  PersonRounded,
  SupervisedUserCircleOutlined,
  SupervisedUserCircleRounded,
} from "@mui/icons-material";

export const moduleSchema = [
  {
    name: "Dashboard",
    section: "Dashboard",
    icon: DashboardOutlined,
    iconOn: DashboardRounded,
    to: "/",
    subCategory: null,
  },
  {
    name: "Users Management",
    section: "users_management",
    icon: SupervisedUserCircleOutlined,
    iconOn: SupervisedUserCircleRounded,
    to: "/users_management",
    subCategory: [
      {
        name: "User Account",
        section: "users_account",
        icon: PersonOutline,
        iconOn: PersonRounded,
        to: "/users_management/users_account",
      },
      {
        name: "Role Management",
        section: "role_management",
        icon: SupervisedUserCircleOutlined,
        iconOn: SupervisedUserCircleRounded,
        to: "/users_management/role_management",
      },
    ],
  },
  {
    name: "Systems",
    section: "systems",
    icon: FeedOutlined,
    iconOn: FeedRounded,
    to: "/systems",
    subCategory: [
      {
        name: "Arcana",
        section: "arcana",
        icon: EventNoteOutlined,
        iconOn: EventNoteRounded,
        to: "/systems/arcana",
      },
      {
        name: "UM",
        section: "um",
        icon: AccountBalanceOutlined,
        iconOn: AccountBalanceRounded,
        to: "/systems/um",
      },
      {
        name: "Ymir",
        section: "ymir",
        icon: ForestOutlined,
        iconOn: ForestRounded,
        to: "/systems/ymir",
      },
      {
        name: "Fisto",
        section: "fisto",
        icon: LeaderboardOutlined,
        iconOn: LeaderboardRounded,
        to: "/systems/fisto",
      },
    ],
  },
];
