import {
  AccountBalanceWalletOutlined,
  AccountBalanceWalletRounded,
  CollectionsBookmarkOutlined,
  CollectionsBookmarkRounded,
  DashboardOutlined,
  DashboardRounded,
  DeveloperBoard,
  FeedOutlined,
  FeedRounded,
  FolderOutlined,
  FolderRounded,
  PersonOutline,
  PersonRounded,
  SupervisedUserCircleOutlined,
  SupervisedUserCircleRounded,
  SupervisorAccountOutlined,
  SupervisorAccountRounded,
  TopicOutlined,
  TopicRounded,
} from "@mui/icons-material";

export const moduleSchema = [
  {
    name: "Dashboard",
    section: "dashboard",
    icon: DashboardOutlined,
    iconOn: DashboardRounded,
    to: "/",
    subCategory: null,
  },

  {
    name: "Users Management",
    section: "users_management",
    icon: SupervisedUserCircleOutlined,
    iconOn: SupervisedUserCircleRounded,
    to: "/users_management",
    subCategory: [
      {
        name: "User Account",
        section: "users_account",
        icon: PersonOutline,
        iconOn: PersonRounded,
        to: "/users_management/users_account",
      },
      {
        name: "Role Management",
        section: "role_management",
        icon: SupervisedUserCircleOutlined,
        iconOn: SupervisedUserCircleRounded,
        to: "/users_management/role_management",
      },
    ],
  },
  {
    name: "System Setup",
    section: "system_setup",
    icon: DeveloperBoard,
    iconOn: DeveloperBoard,
    to: "/system_setup",
    subCategory: null,
  },
  {
    name: "Import/Sync System",
    section: "main_system",
    icon: SupervisorAccountOutlined,
    iconOn: SupervisorAccountRounded,
    to: "/main_system",
    subCategory: null,
  },
  {
    name: "BOA File Manager",
    section: "boa_file_manager",
    icon: TopicOutlined,
    iconOn: TopicRounded,
    to: "/boa_file_manager",
    subCategory: null,
  },
  {
    name: "Book of Accounts",
    section: "boa",
    icon: CollectionsBookmarkOutlined,
    iconOn: CollectionsBookmarkRounded,
    to: "/boa",
    subCategory: null,
  },
  {
    name: "Trial Balance",
    section: "trial_balance",
    icon: AccountBalanceWalletOutlined,
    iconOn: AccountBalanceWalletRounded,
    to: "/trial_balance",
    subCategory: null,
  },
];
